In [104]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [106]:
rain=pd.read_csv("C:\\Users\\ASUS\\Downloads\\archive (3)\\dataset1.csv") 

In [107]:
rain.head()

day  pressure   maxtemp  temparature  mintemp  dewpoint  humidity   cloud   \
0    1     1025.9     19.9         18.3     16.8      13.1         72      49   
1    2     1022.0     21.7         18.9     17.2      15.6         81      83   
2    3     1019.7     20.3         19.3     18.0      18.4         95      91   
3    4     1018.9     22.3         20.6     19.1      18.8         90      88   
4    5     1015.9     21.3         20.7     20.2      19.9         95      81   

  rainfall  sunshine           winddirection  windspeed  
0      yes       9.3                    80.0       26.3  
1      yes       0.6                    50.0       15.3  
2      yes       0.0                    40.0       14.2  
3      yes       1.0                    50.0       16.9  
4      yes       0.0                    40.0       13.7

In [108]:
rain.tail()

day  pressure   maxtemp  temparature  mintemp  dewpoint  humidity   \
361   27     1022.7     18.8         17.7     16.9      15.0         84   
362   28     1026.6     18.6         17.3     16.3      12.8         75   
363   29     1025.9     18.9         17.7     16.4      13.3         75   
364   30     1025.3     19.2         17.3     15.2      13.3         78   
365   31     1026.4     20.5         17.8     15.5      13.0         74   

     cloud  rainfall  sunshine           winddirection  windspeed  
361      90      yes       0.0                    30.0       18.4  
362      85      yes       1.0                    20.0       25.9  
363      78      yes       4.6                    70.0       33.4  
364      86      yes       1.2                    20.0       20.9  
365      66       no       5.7                    20.0       23.3

In [109]:
rain.shape

(366, 12)

In [110]:
rain.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 366 entries, 0 to 365
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   day                     366 non-null    int64  
 1   pressure                366 non-null    float64
 2   maxtemp                 366 non-null    float64
 3   temparature             366 non-null    float64
 4   mintemp                 366 non-null    float64
 5   dewpoint                366 non-null    float64
 6   humidity                366 non-null    int64  
 7   cloud                   366 non-null    int64  
 8   rainfall                366 non-null    object 
 9   sunshine                366 non-null    float64
 10           winddirection  365 non-null    float64
 11  windspeed               365 non-null    float64
dtypes: float64(8), int64(3), object(1)
memory usage: 34.4+ KB


In [111]:
rain.describe()

day    pressure      maxtemp  temparature     mintemp  \
count  366.000000   366.000000  366.000000   366.000000  366.000000   
mean    15.756831  1013.742623   26.191257    23.747268   21.894536   
std      8.823592     6.414776    5.978343     5.632813    5.594153   
min      1.000000   998.500000    7.100000     4.900000    3.100000   
25%      8.000000  1008.500000   21.200000    18.825000   17.125000   
50%     16.000000  1013.000000   27.750000    25.450000   23.700000   
75%     23.000000  1018.100000   31.200000    28.600000   26.575000   
max     31.000000  1034.600000   36.300000    32.400000   30.000000   

         dewpoint   humidity       cloud     sunshine           winddirection  \
count  366.000000  366.000000  366.000000  366.000000              365.000000   
mean    19.989071   80.177596   71.128415    4.419399              101.506849   
std      5.997021   10.062470   21.798012    3.934398               81.723724   
min     -0.400000   36.000000    0.000000    0.000000               10.000000   
25%     16.125000   75.000000   58.000000    0.500000               40.000000   
50%     21.950000   80.500000   80.000000    3.500000               70.000000   
75%     25.000000   87.000000   88.000000    8.200000              190.000000   
max     26.700000   98.000000  100.000000   12.100000              350.000000   

        windspeed  
count  365.000000  
mean    21.536986  
std     10.069712  
min      4.400000  
25%     13.700000  
50%     20.500000  
75%     27.900000  
max     59.500000

In [112]:
rain.dtypes

day                         int64
pressure                  float64
maxtemp                   float64
temparature               float64
mintemp                   float64
dewpoint                  float64
humidity                    int64
cloud                       int64
rainfall                   object
sunshine                  float64
         winddirection    float64
windspeed                 float64
dtype: object

In [113]:
rain.memory_usage()

Index                      132
day                       2928
pressure                  2928
maxtemp                   2928
temparature               2928
mintemp                   2928
dewpoint                  2928
humidity                  2928
cloud                     2928
rainfall                  2928
sunshine                  2928
         winddirection    2928
windspeed                 2928
dtype: int64

In [114]:
rain.columns

Index(['day', 'pressure ', 'maxtemp', 'temparature', 'mintemp', 'dewpoint',
       'humidity ', 'cloud ', 'rainfall', 'sunshine', '         winddirection',
       'windspeed'],
      dtype='object')

In [118]:
rain.rename(columns={'winddirection':'winddirection','temparature':'temperature'},inplace=True)

In [119]:
rain.columns

Index(['day', 'pressure ', 'maxtemp', 'temperature', 'mintemp', 'dewpoint',
       'humidity ', 'cloud ', 'rainfall', 'sunshine', 'winddirection',
       'windspeed'],
      dtype='object')

In [120]:
rain.isna().sum()

day              0
pressure         0
maxtemp          0
temperature      0
mintemp          0
dewpoint         0
humidity         0
cloud            0
rainfall         0
sunshine         0
winddirection    1
windspeed        1
dtype: int64

In [121]:
rain['winddirection']=rain['winddirection'].replace(np.nan,rain['winddirection'].mean())

In [122]:
rain['windspeed']=rain['windspeed'].replace(np.nan,rain['windspeed'].mean())

In [123]:
rain['rainfall']=rain['rainfall'].replace('no',0)

In [124]:
rain['rainfall']=rain['rainfall'].replace('yes',1)

In [125]:
rain.isna().sum()

day              0
pressure         0
maxtemp          0
temperature      0
mintemp          0
dewpoint         0
humidity         0
cloud            0
rainfall         0
sunshine         0
winddirection    0
windspeed        0
dtype: int64

LOGISTIC REGRESSION

In [126]:
y=rain['rainfall']
x=rain.drop(['rainfall','temperature','day'],axis=1)

In [127]:
from sklearn.model_selection import train_test_split

In [128]:
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.7,random_state=2529)

In [129]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((256, 9), (110, 9), (256,), (110,))

In [130]:
from sklearn.linear_model import LogisticRegression

In [131]:
model=LogisticRegression(max_iter=500)

In [132]:
model.fit(x_train,y_train)

LogisticRegression(max_iter=500)

In [133]:
model.intercept_

array([0.00631368])

In [134]:
model.coef_

array([[-4.48081227e-04, -8.87941179e-02, -4.22601740e-01,
         6.42898244e-01, -4.18741734e-02,  4.22671692e-02,
        -1.37676813e-01, -4.16793685e-03,  6.60666502e-02]])

In [135]:
y_pred=model.predict(x_test)

In [136]:
y_pred

array([1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0],
      dtype=int64)

In [137]:
from sklearn.metrics import confusion_matrix,accuracy_score

In [138]:
print('confusion matrix=',confusion_matrix(y_test,y_pred))

confusion matrix= [[18 11]
 [15 66]]


In [139]:
print('accuracy_score=',(accuracy_score(y_test,y_pred)*100))

accuracy_score= 76.36363636363637


Pedictive Analysis

In [140]:
rain.columns

Index(['day', 'pressure ', 'maxtemp', 'temperature', 'mintemp', 'dewpoint',
       'humidity ', 'cloud ', 'rainfall', 'sunshine', 'winddirection',
       'windspeed'],
      dtype='object')

In [141]:
input_data=(1018.9,22.3,19.1,18.8,90,88,1,50,16.9)

In [142]:
input_data_array=np.asarray(input_data)

In [143]:
input_data_array_new=input_data_array.reshape(1,-1)

In [145]:
prediction=model.predict(input_data_array_new)

In [146]:
print(prediction)
if prediction==0:
    print('No Rainfall')
else:
    print('Yes Rainfall')

[1]
Yes Rainfall
